#!/usr/bin/env node
// proto-gen.js — generate Amalgame message classes from a proto3 .proto.
//
//   node tools/proto-gen.js <input.proto> [output.am]
//
// Emits one `public class <Message>` per `message` block, each with
// typed fields + Encode()/Decode() built on amalgame-formats-protobuf's
// ProtoWriter / ProtoReader. The generated file's namespace is derived
// from the .proto `package` (or "Proto" if absent).
//
// Supported (proto3): scalar fields (int32/64, uint32/64, sint32/64,
// fixed32/64, sfixed32/64, bool, string, bytes, float/double-as-bits),
// message fields (nested length-delimited), and `repeated` of any of
// those. NOT yet: enums (treated as int32 — declare them as a peer or
// map to int32 by hand), oneof, map<>, imports, services. Those are
// tracked follow-ups; the generated code is plain AM you can extend.

const fs = require('fs');

const SCALAR = {
  int32:'Varint', int64:'Varint', uint32:'Varint', uint64:'Varint',
  sint32:'Sint', sint64:'Sint',
  bool:'Bool', string:'Str', bytes:'Bytes',
  fixed64:'Fixed64', sfixed64:'Fixed64', double:'Fixed64',
  fixed32:'Fixed32', sfixed32:'Fixed32', float:'Fixed32',
};
const AMTYPE = {
  Varint:'int', Sint:'int', Bool:'bool', Str:'string',
  Bytes:'List<int>', Fixed64:'int', Fixed32:'int',
};
const DEFAULT = {
  int:'0', bool:'false', string:'""', 'List<int>':'new List<int>()',
};

function stripComments(s) {
  return s.replace(/\/\*[\s\S]*?\*\//g, ' ').replace(/\/\/[^\n]*/g, ' ');
}

function parse(src) {
  src = stripComments(src);
  const pkg = (src.match(/package\s+([A-Za-z0-9_.]+)\s*;/) || [])[1] || '';
  const messages = [];
  // Match `message Name { ... }` (non-nested bodies in v0.1).
  const re = /message\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{([^{}]*)\}/g;
  let m;
  while ((m = re.exec(src)) !== null) {
    const name = m[1];
    const fields = [];
    const body = m[2];
    const fre = /(?:(repeated)\s+)?([A-Za-z_][A-Za-z0-9_.]*)\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(\d+)\s*;/g;
    let f;
    while ((f = fre.exec(body)) !== null) {
      fields.push({ repeated: !!f[1], type: f[2], name: f[3], num: parseInt(f[4], 10) });
    }
    messages.push({ name, fields });
  }
  // Match `service Name { rpc M (Req) returns (Resp); ... }`.
  const services = [];
  const sre = /service\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{([^{}]*)\}/g;
  let s;
  while ((s = sre.exec(src)) !== null) {
    const name = s[1];
    const methods = [];
    const rre = /rpc\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(\s*(stream\s+)?([A-Za-z_][A-Za-z0-9_.]*)\s*\)\s*returns\s*\(\s*(stream\s+)?([A-Za-z_][A-Za-z0-9_.]*)\s*\)/g;
    let r;
    while ((r = rre.exec(s[2])) !== null) {
      const reqStream = !!r[2], respStream = !!r[4];
      if (reqStream) { console.error(`note: skipping client-streaming/bidi rpc ${name}.${r[1]} (server-streaming + unary only)`); continue; }
      methods.push({ name: r[1], reqType: r[3], respType: r[5], serverStream: respStream });
    }
    services.push({ name, methods });
  }
  return { pkg, messages, services };
}

function nsFromPackage(pkg) {
  if (!pkg) return 'Proto';
  return pkg.split('.').map(p => p.charAt(0).toUpperCase() + p.slice(1)).join('.');
}

function amType(field) {
  const base = SCALAR[field.type] ? AMTYPE[SCALAR[field.type]] : field.type; // message → its class
  return field.repeated ? `List<${base}>` : base;
}
function defaultFor(field) {
  if (field.repeated) return `new List<${SCALAR[field.type] ? AMTYPE[SCALAR[field.type]] : field.type}>()`;
  const base = SCALAR[field.type] ? AMTYPE[SCALAR[field.type]] : field.type;
  return DEFAULT[base] !== undefined ? DEFAULT[base] : 'null';   // message → null
}
function writeCall(field, valExpr) {
  const w = SCALAR[field.type];
  if (w) return `w.${w}(${field.num}, ${valExpr})`;
  return `w.Message(${field.num}, ${valExpr}.Encode())`;          // message
}
function readExpr(field) {
  const w = SCALAR[field.type];
  if (w) return `r.${w}()`;
  return `${field.type}.Decode(r.Bytes())`;                       // message
}

function gen(parsed) {
  const ns = nsFromPackage(parsed.pkg);
  let out = `// GENERATED by proto-gen.js — do not edit by hand.\n`;
  out += `// Source package: ${parsed.pkg || '(none)'}\n\n`;
  out += `namespace ${ns}\n\n`;
  out += `import Amalgame.Collections\n`;
  out += `import Amalgame.Formats.Protobuf\n`;
  const hasServices = (parsed.services || []).some(s => s.methods.length > 0);
  if (hasServices) out += `import Amalgame.Net.Grpc\n`;
  out += `\n`;

  for (const msg of parsed.messages) {
    out += `public class ${msg.name} {\n`;
    for (const f of msg.fields) out += `    public ${f.name}: ${amType(f)}\n`;
    out += `\n    public ${msg.name}() {\n`;
    for (const f of msg.fields) out += `        this.${f.name} = ${defaultFor(f)}\n`;
    out += `    }\n`;
    out += `    public static ${msg.name} New() { return new ${msg.name}() }\n\n`;

    // Encode
    out += `    public List<int> Encode() {\n        let w = ProtoWriter.New()\n`;
    for (const f of msg.fields) {
      if (f.repeated) {
        out += `        var _i_${f.name}: int = 0\n`;
        out += `        while (_i_${f.name} < this.${f.name}.Count()) {\n`;
        out += `            ${writeCall(f, `this.${f.name}.Get(_i_${f.name})`)}\n`;
        out += `            _i_${f.name} = _i_${f.name} + 1\n        }\n`;
      } else if (!SCALAR[f.type]) {
        // message: skip when null
        out += `        if (this.${f.name} != null) { ${writeCall(f, `this.${f.name}`)} }\n`;
      } else {
        out += `        ${writeCall(f, `this.${f.name}`)}\n`;
      }
    }
    out += `        return w.ToBytes()\n    }\n\n`;

    // Decode
    out += `    public static ${msg.name} Decode(List<int> bytes) {\n`;
    out += `        let m = ${msg.name}.New()\n        let r = ProtoReader.New(bytes)\n`;
    out += `        while (!r.AtEnd()) {\n            let f: int = r.ReadTag()\n`;
    let first = true;
    for (const f of msg.fields) {
      const kw = first ? 'if' : 'else if';
      first = false;
      if (f.repeated) {
        out += `            ${kw} (f == ${f.num}) { m.${f.name}.Add(${readExpr(f)}) }\n`;
      } else {
        out += `            ${kw} (f == ${f.num}) { m.${f.name} = ${readExpr(f)} }\n`;
      }
    }
    out += first ? `            r.Skip()\n` : `            else { r.Skip() }\n`;
    out += `        }\n        return m\n    }\n`;
    out += `}\n\n`;
  }

  // Service stubs: a typed handler holder + RegisterOn(GrpcServer) that
  // decodes the request, calls the typed handler, and encodes the reply.
  for (const svc of (parsed.services || [])) {
    if (svc.methods.length === 0) continue;
    const cls = `${svc.name}Service`;
    const svcPath = (parsed.pkg ? parsed.pkg + '.' : '') + svc.name;   // gRPC path uses the proto package
    out += `// gRPC service ${svcPath} — wire typed handlers, then RegisterOn(server).\n`;
    const htype = (m) => m.serverStream
      ? `Closure<${m.reqType}, List<${m.respType}>>`     // server-streaming: handler returns N replies
      : `Closure<${m.reqType}, ${m.respType}>`;          // unary
    out += `public class ${cls} {\n`;
    for (const mth of svc.methods)
      out += `    public ${mth.name}: ${htype(mth)}\n`;
    out += `\n    public ${cls}() {\n`;
    for (const mth of svc.methods) out += `        this.${mth.name} = null\n`;
    out += `    }\n    public static ${cls} New() { return new ${cls}() }\n\n`;
    // fluent setters
    for (const mth of svc.methods) {
      out += `    public ${cls} On${mth.name}(${htype(mth)} h) { this.${mth.name} = h; return this }\n`;
    }
    out += `\n    // Per-method adapter: decode → typed handler → encode.\n`;
    for (const mth of svc.methods) {
      if (mth.serverStream) {
        out += `    public GrpcStreamReply dispatch${mth.name}(GrpcRequest req) {\n`;
        out += `        if (this.${mth.name} == null) { return GrpcStreamReply.Error(GrpcStatus.Unimplemented(), "${svcPath}/${mth.name} not implemented") }\n`;
        out += `        let inMsg: ${mth.reqType} = ${mth.reqType}.Decode(req.Body)\n`;
        out += `        let outs: List<${mth.respType}> = this.${mth.name}(inMsg)\n`;
        out += `        var frames: List<List<int>> = new List<List<int>>()\n`;
        out += `        var _i: int = 0\n`;
        out += `        while (_i < outs.Count()) { frames.Add(outs.Get(_i).Encode()); _i = _i + 1 }\n`;
        out += `        return GrpcStreamReply.Ok(frames)\n`;
        out += `    }\n`;
      } else {
        out += `    public GrpcReply dispatch${mth.name}(GrpcRequest req) {\n`;
        out += `        if (this.${mth.name} == null) { return GrpcReply.Error(GrpcStatus.Unimplemented(), "${svcPath}/${mth.name} not implemented") }\n`;
        out += `        let inMsg: ${mth.reqType} = ${mth.reqType}.Decode(req.Body)\n`;
        out += `        let outMsg: ${mth.respType} = this.${mth.name}(inMsg)\n`;
        out += `        return GrpcReply.Ok(outMsg.Encode())\n`;
        out += `    }\n`;
      }
    }
    out += `\n    // Register every method on a GrpcServer.\n`;
    out += `    public void RegisterOn(GrpcServer server) {\n`;
    out += `        let svc0 = this\n`;
    for (const mth of svc.methods) {
      const reg = mth.serverStream ? 'RegisterStream' : 'Register';
      out += `        server.${reg}("/${svcPath}/${mth.name}", (r: GrpcRequest) => svc0.dispatch${mth.name}(r))\n`;
    }
    out += `    }\n}\n\n`;

    // Typed client stub: <Name>Client over GrpcClient — one typed method
    // per rpc (unary → Resp; server-streaming → List<Resp>).
    const ccls = `${svc.name}Client`;
    out += `// Typed gRPC client for ${svcPath} — Dial then call methods directly.\n`;
    out += `public class ${ccls} {\n`;
    out += `    public Backend: GrpcClient\n\n`;
    out += `    public ${ccls}(GrpcClient backend) { this.Backend = backend }\n`;
    out += `    public static ${ccls} Dial(string host, int port) { return new ${ccls}(GrpcClient.Dial(host, port)) }\n`;
    out += `    // gRPC over TLS (insecure = skip cert/hostname verification).\n`;
    out += `    public static ${ccls} DialTls(string host, int port, bool insecure) { return new ${ccls}(GrpcClient.DialTls(host, port, insecure)) }\n\n`;
    for (const mth of svc.methods) {
      if (mth.serverStream) {
        out += `    // Server-streaming: returns every reply message.\n`;
        out += `    public List<${mth.respType}> ${mth.name}(${mth.reqType} rq) {\n`;
        out += `        let sreply: GrpcStreamReply = this.Backend.CallStream("/${svcPath}/${mth.name}", rq.Encode())\n`;
        out += `        var outs: List<${mth.respType}> = new List<${mth.respType}>()\n`;
        out += `        var _i: int = 0\n`;
        out += `        while (_i < sreply.Messages.Count()) { outs.Add(${mth.respType}.Decode(sreply.Messages.Get(_i))); _i = _i + 1 }\n`;
        out += `        return outs\n`;
        out += `    }\n`;
      } else {
        out += `    // Unary: returns the decoded reply (check status via a raw\n`;
        out += `    // GrpcClient.Call if you need it).\n`;
        out += `    public ${mth.respType} ${mth.name}(${mth.reqType} rq) {\n`;
        out += `        let reply: GrpcReply = this.Backend.Call("/${svcPath}/${mth.name}", rq.Encode())\n`;
        out += `        return ${mth.respType}.Decode(reply.Body)\n`;
        out += `    }\n`;
      }
    }
    out += `}\n\n`;
  }
  return out;
}

function main() {
  const inp = process.argv[2];
  if (!inp) { console.error('usage: proto-gen.js <input.proto> [output.am]'); process.exit(2); }
  const parsed = parse(fs.readFileSync(inp, 'utf8'));
  const code = gen(parsed);
  const out = process.argv[3];
  if (out) { fs.writeFileSync(out, code); console.error(`wrote ${out} (${parsed.messages.length} message(s))`); }
  else process.stdout.write(code);
}
main();
